// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// corfunexact
SEXP corfunexact(SEXP x, SEXP y, SEXP y0);
RcppExport SEXP treeclim_corfunexact(SEXP xSEXP, SEXP ySEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type y0(y0SEXP);
    __result = Rcpp::wrap(corfunexact(x, y, y0));
    return __result;
END_RCPP
}
// corfunnoboot
SEXP corfunnoboot(SEXP x, SEXP y);
RcppExport SEXP treeclim_corfunnoboot(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    __result = Rcpp::wrap(corfunnoboot(x, y));
    return __result;
END_RCPP
}
// corfun
SEXP corfun(SEXP x, SEXP y);
RcppExport SEXP treeclim_corfun(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    __result = Rcpp::wrap(corfun(x, y));
    return __result;
END_RCPP
}
// pcor
SEXP pcor(SEXP x1, SEXP x2, SEXP y, SEXP y0);
RcppExport SEXP treeclim_pcor(SEXP x1SEXP, SEXP x2SEXP, SEXP ySEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type x2(x2SEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type y0(y0SEXP);
    __result = Rcpp::wrap(pcor(x1, x2, y, y0));
    return __result;
END_RCPP
}
// respoexact
SEXP respoexact(SEXP x, SEXP y, SEXP y0);
RcppExport SEXP treeclim_respoexact(SEXP xSEXP, SEXP ySEXP, SEXP y0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    Rcpp::traits::input_parameter< SEXP >::type y0(y0SEXP);
    __result = Rcpp::wrap(respoexact(x, y, y0));
    return __result;
END_RCPP
}
// respo
SEXP respo(SEXP x, SEXP y);
RcppExport SEXP treeclim_respo(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type y(ySEXP);
    __result = Rcpp::wrap(respo(x, y));
    return __result;
END_RCPP
}
