# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corfun <- function(x, y) {
    .Call('bootres2_corfun', PACKAGE = 'bootres2', x, y)
}

respo <- function(x, y) {
    .Call('bootres2_respo', PACKAGE = 'bootres2', x, y)
}

