# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corfun <- function(x, y) {
    .Call(`_treeclim_corfun`, x, y)
}

corfunexact <- function(x, y, y0) {
    .Call(`_treeclim_corfunexact`, x, y, y0)
}

corfunnoboot <- function(x, y) {
    .Call(`_treeclim_corfunnoboot`, x, y)
}

pcor <- function(x1, x2, y, y0) {
    .Call(`_treeclim_pcor`, x1, x2, y, y0)
}

respo <- function(x, y) {
    .Call(`_treeclim_respo`, x, y)
}

respoexact <- function(x, y, y0) {
    .Call(`_treeclim_respoexact`, x, y, y0)
}

